# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.setGeometry(0, 0, 800, 600)
        MWin.setMinimumSize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon64"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MWin)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.transText = QtWidgets.QPlainTextEdit(self.centralWidget, placeholderText = "Übersetzung")
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.transText.setFont(font)
        self.transText.setObjectName("transText")
        self.mainLayout.addWidget(self.transText, 1, 1, 1, 1)
        self.originText = QtWidgets.QPlainTextEdit(self.centralWidget, placeholderText = "Text")
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.originText.setFont(font)
        self.originText.setObjectName("originText")
        self.mainLayout.addWidget(self.originText, 0, 1, 1, 1)
        self.Layout = QtWidgets.QVBoxLayout()
        self.Layout.setSpacing(6)
        self.Layout.setObjectName("Layout")
        
        self.toggleActionDE = QtWidgets.QAction(None, None, shortcut = "F6", triggered = self.toggleLanguageDE)
        self.addAction(self.toggleActionDE)
        
        self.toggleActionEN = QtWidgets.QAction(None, None, shortcut = "F7", triggered = self.toggleLanguageEN)
        self.addAction(self.toggleActionEN)
        
        self.toggleActionCopy = QtWidgets.QAction(None, None, shortcut = "F8", triggered = self.copySlot)
        self.addAction(self.toggleActionCopy)
        
        self.mainLayout.addLayout(self.Layout, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.mainLayout)
        MWin.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MWin)
        self.menuBar.setStyleSheet("border: 0px;")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MWin.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)
        self.openFile = QtWidgets.QAction(MWin)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/res/images/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFile.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.openFile.setFont(font)
        self.openFile.setObjectName("openFile")
        self.exit = QtWidgets.QAction(MWin)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/res/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon4)
        self.exit.setObjectName("exit")
        self.exportFile = QtWidgets.QAction(MWin)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/res/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportFile.setIcon(icon7)
        self.exportFile.setObjectName("exportFile")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.exportFile)
        self.menuFile.addAction(self.exit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MWin)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "Google Translator"))
        self.menuFile.setTitle(_translate("MWin", "Datei"))
        self.openFile.setText(_translate("MWin", "Öffnen"))
        self.openFile.setShortcut(_translate("MWin", "Ctrl+O"))
        self.exit.setText(_translate("MWin", "Beenden"))
        self.exit.setShortcut(_translate("MWin", "Ctrl+Q"))
        self.exportFile.setText(_translate("MWin", "Export"))
        self.exportFile.setIconText(_translate("MWin", "export"))
        self.exportFile.setShortcut(_translate("MWin", "Ctrl+E"))

import res_rc
